spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://3.37.55.114:3306/nyangflix?useUnicode=yes&characterEncoding=UTF-8"
    username: "nyoung"
    password: "Whgusuddl153!"
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      validation-timeout: 720000
      connection-test-query: select 1
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
